import * as fs from 'fs'
import * as path from 'path'

export interface PrinterProfile {
  id: string
  name: string
  nozzleSize: number
  bedSizeX: number
  bedSizeY: number
  bedSizeZ: number
  maxTemp: number
  maxBedTemp: number
  maxSpeed: number
  defaultSpeed: number
  acceleration: number
}

export interface FilamentProfile {
  id: string
  name: string
  material: string
  extruderTemp: number
  bedTemp: number
  printSpeed: number
  retractDistance: number
  retractSpeed: number
}

export interface PrintSettings {
  layerHeight: number
  infillDensity: number
  shellThickness: number
  supportEnabled: boolean
  fanSpeed: number
}

export interface GcodeGeneratorOptions {
  modelPath: string
  printerProfile: PrinterProfile
  filamentProfile: FilamentProfile
  settings: PrintSettings
}

class StlParser {
  /**
   * Parse ASCII or binary STL file and extract triangles
   * Returns array of triangle vertices for simple analysis
   */
  static parseStl(filePath: string): { vertices: number[][]; bounds: { min: number[]; max: number[] } } {
    const fileBuffer = fs.readFileSync(filePath)

    if (this.isAsciiStl(fileBuffer)) {
      return this.parseAsciiStl(filePath)
    } else {
      return this.parseBinaryStl(fileBuffer)
    }
  }

  private static isAsciiStl(buffer: Buffer): boolean {
    const header = buffer.toString('utf-8', 0, 5)
    return header === 'solid' || buffer.toString('utf-8', 0, 5).match(/\s/) !== null
  }

  private static parseAsciiStl(filePath: string): { vertices: number[][]; bounds: { min: number[]; max: number[] } } {
    const content = fs.readFileSync(filePath, 'utf-8')
    const vertices: number[][] = []
    const vertexPattern = /vertex\s+([-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?)\s+([-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?)\s+([-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?)/g

    let match
    while ((match = vertexPattern.exec(content))) {
      vertices.push([parseFloat(match[1]), parseFloat(match[3]), parseFloat(match[5])])
    }

    return this.calculateBounds(vertices)
  }

  private static parseBinaryStl(buffer: Buffer): { vertices: number[][]; bounds: { min: number[]; max: number[] } } {
    const vertices: number[][] = []
    const numTriangles = buffer.readUInt32LE(80)

    let offset = 84
    for (let i = 0; i < numTriangles; i++) {
      // Skip normal vector (3 floats)
      offset += 12
      // Read 3 vertices (3 floats each)
      for (let j = 0; j < 3; j++) {
        const x = buffer.readFloatLE(offset)
        const y = buffer.readFloatLE(offset + 4)
        const z = buffer.readFloatLE(offset + 8)
        vertices.push([x, y, z])
        offset += 12
      }
      // Skip attribute byte count
      offset += 2
    }

    return this.calculateBounds(vertices)
  }

  private static calculateBounds(
    vertices: number[][],
  ): { vertices: number[][]; bounds: { min: number[]; max: number[] } } {
    const min = [Infinity, Infinity, Infinity]
    const max = [-Infinity, -Infinity, -Infinity]

    for (const vertex of vertices) {
      for (let i = 0; i < 3; i++) {
        if (vertex[i] < min[i]) min[i] = vertex[i]
        if (vertex[i] > max[i]) max[i] = vertex[i]
      }
    }

    return {
      vertices,
      bounds: { min, max },
    }
  }
}

export class GcodeGenerator {
  private static DEFAULT_SETTINGS: PrintSettings = {
    layerHeight: 0.2,
    infillDensity: 20,
    shellThickness: 1.2,
    supportEnabled: false,
    fanSpeed: 100,
  }

  /**
   * Generate G-code from STL model
   */
  static async generate(options: GcodeGeneratorOptions): Promise<string> {
    const settings = { ...this.DEFAULT_SETTINGS, ...options.settings }

    // Parse STL file
    let stlData
    try {
      stlData = StlParser.parseStl(options.modelPath)
    } catch (error) {
      throw new Error(`Failed to parse STL file: ${error}`)
    }

    // Start G-code generation
    const gcode: string[] = []

    // Header and initialization
    gcode.push('; Generated by kuziSlicer')
    gcode.push(`; Printer: ${options.printerProfile.name}`)
    gcode.push(`; Filament: ${options.filamentProfile.name}`)
    gcode.push(`; Layer Height: ${settings.layerHeight}mm`)
    gcode.push('; ============================================================')
    gcode.push('')

    // Set units to mm
    gcode.push('G21')
    // Absolute positioning
    gcode.push('G90')
    // Set acceleration
    gcode.push(`M204 P${options.printerProfile.acceleration} T${options.printerProfile.acceleration}`)

    // Set temperatures
    gcode.push(`M104 S${options.filamentProfile.extruderTemp}`)
    gcode.push(`M140 S${options.filamentProfile.bedTemp}`)
    gcode.push('M109 S' + options.filamentProfile.extruderTemp)
    gcode.push('M190 S' + options.filamentProfile.bedTemp)
    gcode.push('')

    // Home axes
    gcode.push('G28')
    // Move to starting position
    gcode.push('G0 X0 Y0 Z0.2 F2400')
    gcode.push('')

    // Prime nozzle
    gcode.push('; Priming nozzle')
    gcode.push('G92 E0')
    gcode.push('G0 E10 F300')
    gcode.push('G92 E0')
    gcode.push('')

    const bounds = stlData.bounds
    const modelHeight = bounds.max[2] - bounds.min[2]
    const numLayers = Math.ceil(modelHeight / settings.layerHeight)

    // Generate layer commands
    gcode.push(`; Model height: ${modelHeight.toFixed(2)}mm, Layers: ${numLayers}`)
    gcode.push('')

    const feedRate = options.filamentProfile.printSpeed * 60 // Convert mm/s to mm/min

    // ponytail: Basic layer generation, upgrade to voxel-based slicing if accuracy matters
    for (let layer = 0; layer < Math.min(numLayers, 100); layer++) {
      const zHeight = bounds.min[2] + layer * settings.layerHeight
      gcode.push(`; Layer ${layer} / ${numLayers}`)

      // Vary fan speed for first layers
      const fanSpeed = layer < 3 ? 0 : settings.fanSpeed
      gcode.push(`M106 S${Math.round((fanSpeed / 100) * 255)}`)

      // Generate perimeter move for this layer (simplified: rectangular path)
      const insetDistance = options.printerProfile.nozzleSize
      gcode.push(`G0 Z${zHeight.toFixed(3)} F600`)
      gcode.push(
        `G0 X${(bounds.min[0] + insetDistance).toFixed(2)} Y${(bounds.min[1] + insetDistance).toFixed(2)} F3000`,
      )
      gcode.push(`G0 X${(bounds.max[0] - insetDistance).toFixed(2)} Y${(bounds.min[1] + insetDistance).toFixed(2)} F${feedRate}`)
      gcode.push(`G0 X${(bounds.max[0] - insetDistance).toFixed(2)} Y${(bounds.max[1] - insetDistance).toFixed(2)} F${feedRate}`)
      gcode.push(`G0 X${(bounds.min[0] + insetDistance).toFixed(2)} Y${(bounds.max[1] - insetDistance).toFixed(2)} F${feedRate}`)
      gcode.push(`G0 X${(bounds.min[0] + insetDistance).toFixed(2)} Y${(bounds.min[1] + insetDistance).toFixed(2)} F${feedRate}`)

      // Retract if not last layer
      if (layer < numLayers - 1) {
        gcode.push(`G0 E-${options.filamentProfile.retractDistance} F${options.filamentProfile.retractSpeed * 60}`)
      }

      gcode.push('')
    }

    // End sequence
    gcode.push('; End of print')
    gcode.push('M104 S0')
    gcode.push('M140 S0')
    gcode.push('M106 S0')
    gcode.push('G28 X Y')
    gcode.push('M84')

    return gcode.join('\n')
  }

  /**
   * Estimate print time in minutes
   */
  static estimatePrintTime(
    modelPath: string,
    filament: FilamentProfile,
    settings: PrintSettings,
  ): number {
    try {
      const stlData = StlParser.parseStl(modelPath)
      const bounds = stlData.bounds
      const modelHeight = bounds.max[2] - bounds.min[2]
      const modelArea = (bounds.max[0] - bounds.min[0]) * (bounds.max[1] - bounds.min[1])

      const numLayers = modelHeight / settings.layerHeight
      const perimetersPerLayer = 2 * ((bounds.max[0] - bounds.min[0]) + (bounds.max[1] - bounds.min[1]))
      const infillFraction = settings.infillDensity / 100
      const layerDistance = perimetersPerLayer + modelArea * infillFraction * 0.1 // Simplified

      const totalDistance = layerDistance * numLayers
      const timeMinutes = totalDistance / (filament.printSpeed * 60)

      return Math.round(timeMinutes + numLayers * 0.1) // Add layer change time
    } catch {
      return 0
    }
  }

  /**
   * Estimate filament weight in grams
   */
  static estimateFilamentWeight(
    modelPath: string,
    filament: FilamentProfile,
    settings: PrintSettings,
  ): number {
    try {
      const stlData = StlParser.parseStl(modelPath)
      const bounds = stlData.bounds
      const modelHeight = bounds.max[2] - bounds.min[2]
      const modelArea = (bounds.max[0] - bounds.min[0]) * (bounds.max[1] - bounds.min[1])

      const numLayers = modelHeight / settings.layerHeight
      const layerVolume = modelArea * settings.layerHeight
      const filledVolume = layerVolume * (settings.infillDensity / 100 + 0.3) // 0.3 for walls

      const totalVolume = filledVolume * numLayers
      const density = filament.material === 'PLA' ? 1.24 : filament.material === 'PETG' ? 1.27 : 1.05

      return Math.round(totalVolume * density)
    } catch {
      return 0
    }
  }
}
