import { createHash } from 'crypto'
import { unzipSync, strFromU8 } from 'fflate'
import type { PreparedPrint } from '../core/types'
import GcodeValidationEngine from '../../main/services/engines/gcodeValidationEngine'

/** Validate an already sliced project, preserving all original entries and the actual plate. */
export function prepare(bytes: Uint8Array, nozzle: number): PreparedPrint {
  if (![0.2, 0.4, 0.6].includes(nozzle)) throw new Error('Unsupported nozzle')
  if (!bytes.length || bytes.length > 64 * 1024 * 1024) throw new Error('Project size must be between 1 byte and 64 MiB')
  let expanded = 0
  const entries = unzipSync(bytes, { filter(entry) {
    expanded += entry.originalSize
    if (expanded > 128 * 1024 * 1024 || /(^|\/)\.\.(\/|$)|^[/\\]|\\/.test(entry.name)) throw new Error('Unsafe archive entry or expansion size')
    return true
  } })
  const plates = Object.keys(entries).filter(name => /^Metadata\/plate_\d+\.gcode$/.test(name))
  if (plates.length !== 1) throw new Error('Select an export containing exactly one sliced plate')
  const plate = plates[0]
  const text = (name: string) => {
    if (!entries[name]) throw new Error(`Missing project entry: ${name}`)
    return strFromU8(entries[name])
  }
  const settings = JSON.parse(text('Metadata/project_settings.config'))
  if (settings.printer_model !== 'Bambu Lab A1 mini') throw new Error('Project is not sliced for Bambu Lab A1 mini')
  if (!Array.isArray(settings.nozzle_diameter) || settings.nozzle_diameter.length !== 1 || Number(settings.nozzle_diameter[0]) !== nozzle) throw new Error('Project nozzle mismatch; re-slice for the installed nozzle')
  const slice = text('Metadata/slice_info.config')
  const plateNumber = plate.match(/plate_(\d+)/)?.[1]
  for (const [key, value] of [['index', plateNumber], ['printer_model_id', 'N1'], ['nozzle_diameters', String(nozzle)]]) {
    if (!slice.includes(`key="${key}" value="${value}"`)) throw new Error(`Slice metadata mismatch: ${key}`)
  }
  const expected = text(`${plate}.md5`).trim().toLowerCase()
  const actual = createHash('md5').update(entries[plate]).digest('hex')
  if (expected !== actual) throw new Error('G-code checksum mismatch')
  const gcode = text(plate)
  const validation = GcodeValidationEngine.validateForPrint(gcode)
  if (!validation.valid) throw new Error(validation.errors.join(' '))
  if (!/^;\s*(?:BambuStudio|generated by OrcaSlicer)/im.test(gcode)) throw new Error('A native Bambu/Orca sliced project is required')
  const height = Number(gcode.match(/^;\s*max_z_height:\s*([\d.]+)/m)?.[1])
  if (!Number.isFinite(height) || height <= 0 || height > 180) throw new Error('Object height is unknown or exceeds build volume')
  for (const raw of gcode.split(/\r?\n/)) {
    const line = raw.split(';')[0].trim()
    // Native A1 mini start code uses M500 to save its own calibration data.
    if (/^(?:M112|M502|M997|M999)\b/i.test(line)) throw new Error('Reset, firmware, emergency or persistent configuration command in project')
    const heat = line.match(/^M(104|109|140|190)\b.*?\b[SR](-?[\d.]+)/i)
    if (heat) {
      const temperature = Number(heat[2]), limit = ['140', '190'].includes(heat[1]) ? 80 : 300
      if (!Number.isFinite(temperature) || temperature < 0 || temperature > limit) throw new Error('Temperature exceeds printer limits')
    }
  }
  return { bytes: Uint8Array.from(bytes), sha256: createHash('sha256').update(bytes).digest('hex'), plate, nozzle, model: 'Bambu Lab A1 mini' }
}
