export interface GcodeValidationResult {
  valid: boolean
  errors: ReadonlyArray<string>
}

export class GcodeValidationEngine {
  static validateForPrint(gcode: string): GcodeValidationResult {
    const errors: string[] = []
    if (!gcode.trim()) errors.push('G-code is empty.')
    if (/Generated by kuziSlicer/i.test(gcode)) errors.push('Prototype kuziSlicer G-code cannot be sent to a printer.')
    if (!/^\s*M(?:104|109)\s/m.test(gcode)) errors.push('No nozzle heating command was found.')
    if (!/^\s*M(?:140|190)\s/m.test(gcode)) errors.push('No bed heating command was found.')
    if (!/^\s*G(?:0|1)\s/m.test(gcode)) errors.push('No movement commands were found.')
    if (!/^\s*G1\b[^;\r\n]*\bE-?\d/m.test(gcode)) errors.push('No extrusion moves were found.')
    if (/^\s*BED_MESH_CALIBRATE\b/im.test(gcode)) errors.push('BED_MESH_CALIBRATE is not allowed in uploaded print files.')
    return { valid: errors.length === 0, errors }
  }
}

export default GcodeValidationEngine
