/**
 * G-code Engine — pure math for G-code generation.
 * Takes parsed geometry + profiles + settings, returns G-code string.
 * No I/O, no plugin calls. Pure algorithmic logic.
 */

import type { PrinterProfile, FilamentProfile, PrintSettings } from '../gcodeGenerator'
import type { StlGeometry } from './stlEngine'
import SliceEngine, { Contour, Point2 } from './sliceEngine'
import { getPattern, solidFill, spacingForDensity, Segment } from './infill'

export interface GcodeEngineOptions {
  geometry: StlGeometry
  printer: PrinterProfile
  filament: FilamentProfile
  settings: PrintSettings
}

const FILAMENT_DIAMETER = 1.75 // ponytail: assumes standard 1.75mm filament; add a profile field if alt diameters are needed
const SKIN_LAYERS = 3 // solid top/bottom layers

export class GcodeEngine {
  private static readonly DEFAULT_SETTINGS: PrintSettings = {
    layerHeight: 0.2,
    infillDensity: 20,
    infillPattern: 'grid',
    shellThickness: 1.2,
    supportEnabled: false,
    fanSpeed: 100,
  }

  /**
   * Generate G-code from parsed geometry.
   * Pure function: no I/O, no side effects.
   */
  static generate(opts: GcodeEngineOptions): string {
    const settings = { ...this.DEFAULT_SETTINGS, ...opts.settings }
    const gcode: string[] = []

    const lineWidth = opts.printer.nozzleSize
    const filamentArea = Math.PI * (FILAMENT_DIAMETER / 2) ** 2
    const feedRate = Math.round(opts.filament.printSpeed * 60) // mm/s → mm/min
    const travelRate = Math.round(opts.printer.maxSpeed * 60)
    const pattern = getPattern(settings.infillPattern)

    // Model sits on the bed: shift so the lowest point is z=0, and centre it on the plate.
    const bounds = opts.geometry.bounds
    const offsetX = opts.printer.bedSizeX / 2 - (bounds.min[0] + bounds.max[0]) / 2
    const offsetY = opts.printer.bedSizeY / 2 - (bounds.min[1] + bounds.max[1]) / 2
    const offsetZ = -bounds.min[2]

    const layers = SliceEngine.sliceMesh(opts.geometry, settings.layerHeight)
    const perimeterCount = Math.max(1, Math.round(settings.shellThickness / lineWidth))

    // An open or non-manifold mesh yields no closed loops to trace. Failing loudly beats
    // handing the user a G-code file that runs the printer through an empty print.
    if (!layers.some((layer) => layer.contours.length > 0)) {
      throw new Error(
        'No printable cross-sections found. The model is probably not a closed solid ' +
          '(open edges, holes or a surface-only mesh) — repair it and try again.'
      )
    }

    // Header
    gcode.push('; Generated by kuziSlicer')
    gcode.push(`; Printer: ${opts.printer.name}`)
    gcode.push(`; Filament: ${opts.filament.name}`)
    gcode.push(`; Layer Height: ${settings.layerHeight}mm`)
    gcode.push(`; Infill: ${settings.infillDensity}% ${pattern.name}`)
    gcode.push(`; Perimeters: ${perimeterCount}`)
    gcode.push(`; Layers: ${layers.length}`)
    gcode.push('; ============================================================')
    gcode.push('')

    // Init
    gcode.push('G21') // mm
    gcode.push('G90') // absolute
    gcode.push('M83') // relative extrusion -- keeps E from growing unbounded over a long print
    gcode.push(`M204 P${opts.printer.acceleration} T${opts.printer.acceleration}`)
    gcode.push('')

    // Temps
    gcode.push(`M104 S${opts.filament.extruderTemp}`)
    gcode.push(`M140 S${opts.filament.bedTemp}`)
    gcode.push(`M109 S${opts.filament.extruderTemp}`)
    gcode.push(`M190 S${opts.filament.bedTemp}`)
    gcode.push('')

    // Home + prime
    gcode.push('G28')
    gcode.push('G92 E0')
    gcode.push('G1 Z0.2 F600')
    gcode.push('')

    let position: Point2 | null = null
    let retracted = false

    const extrusionFor = (distance: number) =>
      (distance * settings.layerHeight * lineWidth) / filamentArea

    const travelTo = (target: Point2) => {
      if (position && Math.hypot(target.x - position.x, target.y - position.y) < 1e-6) return
      if (!retracted && position) {
        gcode.push(`G1 E-${opts.filament.retractDistance.toFixed(4)} F${Math.round(opts.filament.retractSpeed * 60)}`)
        retracted = true
      }
      gcode.push(`G0 X${target.x.toFixed(3)} Y${target.y.toFixed(3)} F${travelRate}`)
      position = target
    }

    const extrudeTo = (target: Point2) => {
      if (!position) {
        travelTo(target)
        return
      }
      const distance = Math.hypot(target.x - position.x, target.y - position.y)
      if (distance < 1e-6) return
      if (retracted) {
        gcode.push(`G1 E${opts.filament.retractDistance.toFixed(4)} F${Math.round(opts.filament.retractSpeed * 60)}`)
        retracted = false
      }
      gcode.push(
        `G1 X${target.x.toFixed(3)} Y${target.y.toFixed(3)} E${extrusionFor(distance).toFixed(5)} F${feedRate}`
      )
      position = target
    }

    const place = (p: Point2): Point2 => ({ x: p.x + offsetX, y: p.y + offsetY })

    const drawLoop = (contour: Contour) => {
      travelTo(place(contour[0]))
      for (let i = 1; i < contour.length; i++) extrudeTo(place(contour[i]))
      extrudeTo(place(contour[0])) // close the loop
    }

    const drawSegments = (segments: Segment[]) => {
      for (const [from, to] of segments) {
        travelTo(place(from))
        extrudeTo(place(to))
      }
    }

    for (let index = 0; index < layers.length; index++) {
      const layer = layers[index]
      if (layer.contours.length === 0) continue

      gcode.push(`; Layer ${index + 1}/${layers.length}`)
      gcode.push(`G1 Z${(layer.z + offsetZ).toFixed(3)} F600`)
      if (index === 0) gcode.push('M106 S0')
      else if (index === SKIN_LAYERS) gcode.push(`M106 S${Math.round((settings.fanSpeed / 100) * 255)}`)

      // Perimeters, outermost first, each inset half a line width from the last.
      let loops = layer.contours.map((c) => SliceEngine.offsetContour(c, lineWidth / 2)).filter((c) => c.length >= 3)
      for (let shell = 0; shell < perimeterCount && loops.length > 0; shell++) {
        // Feature markers follow the PrusaSlicer/Cura convention so the preview (and any
        // third-party G-code viewer) can colour moves by what they are.
        gcode.push(shell === 0 ? ';TYPE:WALL-OUTER' : ';TYPE:WALL-INNER')
        for (const loop of loops) drawLoop(loop)
        if (shell < perimeterCount - 1) {
          loops = loops.map((c) => SliceEngine.offsetContour(c, lineWidth)).filter((c) => c.length >= 3)
        }
      }

      // Infill fills whatever is left inside the innermost perimeter.
      const infillArea = loops
        .map((c) => SliceEngine.offsetContour(c, lineWidth))
        .filter((c) => c.length >= 3)
      if (infillArea.length > 0) {
        const isSkin = index < SKIN_LAYERS || index >= layers.length - SKIN_LAYERS
        if (isSkin) {
          gcode.push(';TYPE:SKIN')
          drawSegments(solidFill(infillArea, lineWidth, index))
        } else if (settings.infillDensity > 0) {
          gcode.push(';TYPE:FILL')
          drawSegments(
            pattern.generate({
              contours: infillArea,
              spacing: spacingForDensity(lineWidth, settings.infillDensity),
              layerIndex: index,
            })
          )
        }
      }

      gcode.push('')
    }

    // End
    gcode.push('; End of print')
    gcode.push(`G1 E-${opts.filament.retractDistance.toFixed(4)} F${Math.round(opts.filament.retractSpeed * 60)}`)
    gcode.push('M104 S0')
    gcode.push('M140 S0')
    gcode.push('M106 S0')
    gcode.push('G28 X Y')
    gcode.push('M84')

    return gcode.join('\n')
  }

  /**
   * Estimate print time (minutes).
   * Pure function based on geometry + filament + settings.
   */
  static estimatePrintTime(
    geometry: StlGeometry,
    filament: FilamentProfile,
    settings: PrintSettings
  ): number {
    const bounds = geometry.bounds
    const modelHeight = bounds.max[2] - bounds.min[2]
    const modelArea = (bounds.max[0] - bounds.min[0]) * (bounds.max[1] - bounds.min[1])

    const numLayers = modelHeight / settings.layerHeight
    const perimetersPerLayer = 2 * ((bounds.max[0] - bounds.min[0]) + (bounds.max[1] - bounds.min[1]))
    const infillFraction = settings.infillDensity / 100
    const layerDistance = perimetersPerLayer + modelArea * infillFraction * 0.1

    const totalDistance = layerDistance * numLayers
    const timeMinutes = totalDistance / (filament.printSpeed * 60)

    return Math.round(timeMinutes + numLayers * 0.1)
  }

  /**
   * Estimate filament weight (grams).
   * Pure function based on geometry + filament + settings.
   */
  static estimateFilamentWeight(
    geometry: StlGeometry,
    filament: FilamentProfile,
    settings: PrintSettings
  ): number {
    const bounds = geometry.bounds
    const modelHeight = bounds.max[2] - bounds.min[2]
    const modelArea = (bounds.max[0] - bounds.min[0]) * (bounds.max[1] - bounds.min[1])

    const numLayers = modelHeight / settings.layerHeight
    const layerVolume = modelArea * settings.layerHeight
    const filledVolume = layerVolume * (settings.infillDensity / 100 + 0.3)

    const totalVolume = filledVolume * numLayers
    const density =
      filament.material === 'PLA' ? 1.24 : filament.material === 'PETG' ? 1.27 : 1.05

    return Math.round(totalVolume * density)
  }
}

export default GcodeEngine
