/**
 * G-code Engine — pure math for G-code generation.
 * Takes parsed geometry + profiles + settings, returns G-code string.
 * No I/O, no plugin calls. Pure algorithmic logic.
 */

import type { PrinterProfile, FilamentProfile, PrintSettings } from '../gcodeGenerator'
import type { StlGeometry } from './stlEngine'

export interface GcodeEngineOptions {
  geometry: StlGeometry
  printer: PrinterProfile
  filament: FilamentProfile
  settings: PrintSettings
}

export class GcodeEngine {
  private static readonly DEFAULT_SETTINGS: PrintSettings = {
    layerHeight: 0.2,
    infillDensity: 20,
    shellThickness: 1.2,
    supportEnabled: false,
    fanSpeed: 100,
  }

  /**
   * Generate G-code from parsed geometry.
   * Pure function: no I/O, no side effects.
   */
  static generate(opts: GcodeEngineOptions): string {
    const settings = { ...this.DEFAULT_SETTINGS, ...opts.settings }
    const gcode: string[] = []

    // Header
    gcode.push('; Generated by kuziSlicer')
    gcode.push(`; Printer: ${opts.printer.name}`)
    gcode.push(`; Filament: ${opts.filament.name}`)
    gcode.push(`; Layer Height: ${settings.layerHeight}mm`)
    gcode.push('; ============================================================')
    gcode.push('')

    // Init
    gcode.push('G21') // mm
    gcode.push('G90') // absolute
    gcode.push(`M204 P${opts.printer.acceleration} T${opts.printer.acceleration}`)
    gcode.push('')

    // Temps
    gcode.push(`M104 S${opts.filament.extruderTemp}`)
    gcode.push(`M140 S${opts.filament.bedTemp}`)
    gcode.push('M109 S' + opts.filament.extruderTemp)
    gcode.push('M190 S' + opts.filament.bedTemp)
    gcode.push('')

    // Home + prime
    gcode.push('G28')
    gcode.push('G0 X0 Y0 Z0.2 F2400')
    gcode.push('')
    gcode.push('; Priming nozzle')
    gcode.push('G92 E0')
    gcode.push('G0 E10 F300')
    gcode.push('G92 E0')
    gcode.push('')

    // Layers
    const bounds = opts.geometry.bounds
    const modelHeight = bounds.max[2] - bounds.min[2]
    const numLayers = Math.ceil(modelHeight / settings.layerHeight)
    const feedRate = opts.filament.printSpeed * 60 // mm/s → mm/min

    gcode.push(`; Model height: ${modelHeight.toFixed(2)}mm, Layers: ${numLayers}`)
    gcode.push('')

    // ponytail: basic rectangular perimeter per layer. Upgrade to voxel slicing + Arachne perimeters when Phase 1 ready.
    for (let layer = 0; layer < Math.min(numLayers, 100); layer++) {
      const zHeight = bounds.min[2] + layer * settings.layerHeight
      gcode.push(`; Layer ${layer} / ${numLayers}`)

      const fanSpeed = layer < 3 ? 0 : settings.fanSpeed
      gcode.push(`M106 S${Math.round((fanSpeed / 100) * 255)}`)

      const insetDistance = opts.printer.nozzleSize
      gcode.push(`G0 Z${zHeight.toFixed(3)} F600`)
      gcode.push(
        `G0 X${(bounds.min[0] + insetDistance).toFixed(2)} Y${(bounds.min[1] + insetDistance).toFixed(2)} F3000`
      )
      gcode.push(
        `G0 X${(bounds.max[0] - insetDistance).toFixed(2)} Y${(bounds.min[1] + insetDistance).toFixed(2)} F${feedRate}`
      )
      gcode.push(
        `G0 X${(bounds.max[0] - insetDistance).toFixed(2)} Y${(bounds.max[1] - insetDistance).toFixed(2)} F${feedRate}`
      )
      gcode.push(
        `G0 X${(bounds.min[0] + insetDistance).toFixed(2)} Y${(bounds.max[1] - insetDistance).toFixed(2)} F${feedRate}`
      )
      gcode.push(
        `G0 X${(bounds.min[0] + insetDistance).toFixed(2)} Y${(bounds.min[1] + insetDistance).toFixed(2)} F${feedRate}`
      )

      if (layer < numLayers - 1) {
        gcode.push(
          `G0 E-${opts.filament.retractDistance} F${opts.filament.retractSpeed * 60}`
        )
      }

      gcode.push('')
    }

    // End
    gcode.push('; End of print')
    gcode.push('M104 S0')
    gcode.push('M140 S0')
    gcode.push('M106 S0')
    gcode.push('G28 X Y')
    gcode.push('M84')

    return gcode.join('\n')
  }

  /**
   * Estimate print time (minutes).
   * Pure function based on geometry + filament + settings.
   */
  static estimatePrintTime(
    geometry: StlGeometry,
    filament: FilamentProfile,
    settings: PrintSettings
  ): number {
    const bounds = geometry.bounds
    const modelHeight = bounds.max[2] - bounds.min[2]
    const modelArea = (bounds.max[0] - bounds.min[0]) * (bounds.max[1] - bounds.min[1])

    const numLayers = modelHeight / settings.layerHeight
    const perimetersPerLayer = 2 * ((bounds.max[0] - bounds.min[0]) + (bounds.max[1] - bounds.min[1]))
    const infillFraction = settings.infillDensity / 100
    const layerDistance = perimetersPerLayer + modelArea * infillFraction * 0.1

    const totalDistance = layerDistance * numLayers
    const timeMinutes = totalDistance / (filament.printSpeed * 60)

    return Math.round(timeMinutes + numLayers * 0.1)
  }

  /**
   * Estimate filament weight (grams).
   * Pure function based on geometry + filament + settings.
   */
  static estimateFilamentWeight(
    geometry: StlGeometry,
    filament: FilamentProfile,
    settings: PrintSettings
  ): number {
    const bounds = geometry.bounds
    const modelHeight = bounds.max[2] - bounds.min[2]
    const modelArea = (bounds.max[0] - bounds.min[0]) * (bounds.max[1] - bounds.min[1])

    const numLayers = modelHeight / settings.layerHeight
    const layerVolume = modelArea * settings.layerHeight
    const filledVolume = layerVolume * (settings.infillDensity / 100 + 0.3)

    const totalVolume = filledVolume * numLayers
    const density =
      filament.material === 'PLA' ? 1.24 : filament.material === 'PETG' ? 1.27 : 1.05

    return Math.round(totalVolume * density)
  }
}

export default GcodeEngine
